# Generated by Django 5.1.3 on 2024-11-14 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='spotify_id',
            field=models.CharField(default='default_spotify_id', max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='spotify_id',
            field=models.CharField(default='default_spotify_id', max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='track',
            name='spotify_id',
            field=models.CharField(default='default_spotify_id', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
