# Generated by Django 5.1.3 on 2024-11-14 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_album_spotify_id_artist_spotify_id_track_spotify_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='duration_ms',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
