# Generated by Django 5.1.3 on 2024-11-27 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_track_duration_ms'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='playlist_covers/'),
        ),
    ]
