# Generated by Django 5.1.3 on 2024-11-27 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_playlist_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='cover',
        ),
    ]
