# Generated by Django 5.1.3 on 2024-11-27 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_remove_playlist_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='cover_image',
        ),
    ]
