# Generated by Django 5.1.3 on 2024-11-29 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_playlist_description_playlist_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='track_file',
        ),
        migrations.AlterField(
            model_name='track',
            name='spotify_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
