# Generated by Django 5.1.3 on 2024-11-29 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0011_track_preview_url_alter_artist_spotify_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='preview_url',
        ),
        migrations.AddField(
            model_name='track',
            name='track_file',
            field=models.FileField(blank=True, null=True, upload_to='track_files/'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='spotify_id',
            field=models.CharField(default='default_spotify_id', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='spotify_id',
            field=models.CharField(default='default_spotify_id', max_length=50, unique=True),
        ),
    ]
