# Generated by Django 5.1.3 on 2024-11-29 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0012_remove_track_preview_url_track_track_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='description',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='image_url',
        ),
    ]
