# Generated by Django 5.1.3 on 2024-11-30 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0013_remove_playlist_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='preview_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
