# Generated by Django 5.1.3 on 2024-12-04 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0015_alter_artist_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='track_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='track',
            name='track_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
